name: Download and Upload File

on:
  workflow_dispatch:
    inputs:
      file_url:
        description: 'لینک فایل برای دانلود'
        required: true

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download file
        run: |
          wget "${{ github.event.inputs.file_url }}" -O downloaded_file

      - name: Commit and push file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add downloaded_file
          git commit -m "Add downloaded file" || echo "No changes"
          git push
